### ISSUE TITLE
Improved UI/UX!

### ISSUE THREAD

**Issue by Khushik514** [Khushik514/chat-bot-design#1]
Improve the UI/UX of the chat bot and other features are welcomed!

**Comment by Ramlanisagar** [comment]
@Khushik514 can I add a button for switch between dark and light theme.

**Comment by Ramlanisagar** [comment]
or a color picker through which user can select color of background according to their choice.please let me know if any of these changes are required.

**Comment by Khushik514** [comment]
> or a color picker through which user can select color of background according to their choice.please let me know if any of these changes are required.

Sure. The light and dark theme button idea looks good. Please go ahead and thanks a lot.

**Comment by Ramlanisagar** [comment]
task done @Khushik514 please review my PR #2

**Comment by Khushik514** [comment]
> task done @Khushik514 please review my PR #2

Thank you for the PR. The PR is merged :)
